"use client";
import {useMemo,useState} from "react";
import {FileSearch,ArrowDownRight} from "lucide-react";
import {ResponsiveContainer,LineChart,Line,CartesianGrid,XAxis,YAxis,Tooltip} from "recharts";
import {Badge} from "./workspace";
import type {AuditResult} from "./audit";
import {auditSeries,buildAuditCurve} from "@/lib/audit-chart";
import {pct,usd,num,day} from "@/lib/format";
import {costVerdict} from "@/lib/audit-guide";
const periodTime=(ts:number)=>new Date(ts*1000).toLocaleString("en-GB",{timeZone:"UTC",dateStyle:"medium",timeStyle:"short"});
const performance=(valid:boolean,value:number|null)=>valid&&value!==null&&Number.isFinite(value)?value:null;

export default function AuditComparison({audit}:{audit:AuditResult}){
  const [evidence,setEvidence]=useState("strategy"),[trade,setTrade]=useState("");
  const row=audit.results[evidence];
  const curve=useMemo(()=>buildAuditCurve(audit.results),[audit]);
  const training=audit.phase==="training";
  const labels=Object.fromEntries(auditSeries.map(s=>[s.key,s.label]));
  const strategy=audit.results.strategy,verdict=costVerdict(strategy.valid,strategy.metrics.gross_return_pct,strategy.metrics.net_return_pct),selectedTrade=row.trades.find(t=>t.id===trade);
  return <section id={`${training?"training":"holdout"}-results`} tabIndex={-1} className={`panel audit-comparison ${training?"training-result":"holdout-result"}`}>
    <div className="panel-heading"><div><div className="eyebrow">{training?"LEARN FROM TRAINING":"THE LOCKED EVALUATION"}</div><h2>{training?"Training results":"Historical holdout results"}</h2><p>{periodTime(row.start_ts)} → {periodTime(row.end_ts)} · UTC · {training?"In sample":"Out of sample"}</p></div><Badge kind={audit.dataset_kind}/></div>
    <div className="audit-verdict"><span className="small-label">IN PLAIN WORDS</span><h3>{verdict.title}</h3><p>{verdict.detail}</p>{performance(strategy.valid,strategy.metrics.gross_return_pct)!==null&&performance(strategy.valid,strategy.metrics.net_return_pct)!==null&&<p className="verdict-numbers">Before costs: <b>{pct(strategy.metrics.gross_return_pct)}</b><span>After costs: <b>{pct(strategy.metrics.net_return_pct)}</b></span></p>}<small>{training?"Training is the earlier period used to inspect settings. The separate later-period result comes after freezing.":"Holdout is the separate later historical period. This comparison does not establish alpha or future profitability."}{audit.dataset_kind==="SYNTHETIC"?" All observations here are simulated.":""}</small></div>
    <div className="audit-return-grid">{auditSeries.map(({key,label,color})=>{const r=audit.results[key];if(!r)return null;const net=performance(r.valid,r.metrics.net_return_pct);return <div className="audit-return" key={key}><span><i style={{background:color}}/>{label}</span><strong className={net==null?"":net<0?"negative":"positive"}>{pct(net)}</strong><small>Net after modeled costs</small><p className="benchmark-caption">{key==="strategy"?"Follow the selected wallet hypothesis.":key==="buy_and_hold"?"Fixed allocation, held to period end.":"Buy after a pre-specified price rise."}</p><div><span>Gross <b>{pct(performance(r.valid,r.metrics.gross_return_pct))}</b></span><span>Costs <b>{usd(performance(r.valid,r.metrics.costs_usd))}</b></span></div></div>;})}</div>
    <div className="audit-equity-heading"><h3>Same period. Three portfolios.</h3><span>Net equity · USD</span></div>
    {curve.length>1?<div className="audit-equity chart" role="img" aria-label="Net equity over time for the wallet hypothesis, buy-and-hold and simple momentum. Exact returns and activity are provided in the comparison table below."><ResponsiveContainer width="100%" height="100%"><LineChart data={curve} margin={{top:12,right:12,bottom:0,left:6}}><CartesianGrid stroke="#2a3033" vertical={false} strokeDasharray="3 5"/><XAxis dataKey="ts" type="number" domain={["dataMin","dataMax"]} tickFormatter={day} tick={{fill:"#a8b2b3",fontSize:12}} axisLine={false} tickLine={false} minTickGap={42}/><YAxis domain={["auto","auto"]} tickFormatter={v=>`$${num(Number(v),0)}`} width={82} tick={{fill:"#a8b2b3",fontSize:12}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:"#171d20",border:"1px solid #3a4548",borderRadius:12,color:"#edf1ef",fontSize:13}} labelFormatter={v=>new Date(Number(v)*1000).toLocaleString("en-GB",{timeZone:"UTC"})+" UTC"} formatter={(value,name)=>[usd(Number(value)),String(name)]}/>{auditSeries.map(({key,label,color})=><Line key={key} dataKey={key} name={label} stroke={color} strokeWidth={key==="strategy"?2.5:1.8} strokeDasharray={key==="momentum"?"5 4":undefined} type="linear" dot={false} connectNulls={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div>:<p className="chart-unavailable">Insufficient observations to draw a comparison. Inspect coverage and exclusions below.</p>}
    <div className="chart-legend audit-legend">{auditSeries.map(s=><span key={s.key}><i style={{background:s.color}}/>{s.label}</span>)}</div><p className="fine-print">All curves use the same execution engine and modeled costs. Missing observations remain gaps. Exposure and trading activity can differ.</p>
    <div className="audit-findings"><div><FileSearch size={19}/><h3>What this period tells us</h3></div><ul>{audit.findings.map(f=><li key={f}>{f}</li>)}</ul><p className="fine-print">A positive result in this period does not establish alpha.</p></div>
    <div className="panel-heading comparison-heading"><h3>The full comparison</h3><span className="small-label">RETURNS + ACTIVITY + COSTS</span></div>
    <div className="table-wrap"><table><caption className="sr-only">Portfolio returns, modeled costs, drawdown and activity in this evaluation period</caption><thead><tr><th>Portfolio</th><th>Gross return</th><th>Net after costs</th><th>Costs</th><th>Drawdown</th><th>Trades</th><th>Exposure</th><th>Turnover</th><th>Failed executions</th></tr></thead><tbody>{Object.entries(audit.results).map(([k,r])=><tr key={k}><td>{labels[k]||k}</td><td>{pct(performance(r.valid,r.metrics.gross_return_pct))}</td><td>{pct(performance(r.valid,r.metrics.net_return_pct))}</td><td>{usd(performance(r.valid,r.metrics.costs_usd))}</td><td>{pct(performance(r.valid,r.metrics.max_drawdown_pct))}</td><td>{r.metrics.trade_count}</td><td>{pct(performance(r.valid,r.activity.time_weighted_exposure_pct))}</td><td>{num(r.activity.round_trip_turnover_x,2)}×</td><td>{r.activity.failed_execution_count}</td></tr>)}</tbody></table></div>
    <details><summary>Benchmark methodology and activity definitions</summary>{Object.values(audit.benchmarks).map(b=><div className="audit-method" key={b.name}><h3>{b.name}</h3><p>{b.rule}</p><p>{b.allocation}</p></div>)}<p>Allocation per token: {usd(audit.benchmark_allocation_usd)}. Exposure is time-weighted marked holdings / equity. Turnover is entry plus exit notional / starting capital. Failed executions count engine exclusions, including liquidity failures and unfilled orders; they are not submitted transactions.</p></details>
    <div className="trade-evidence-heading"><ArrowDownRight size={19}/><h3>Follow the evidence to a trade</h3></div>
    <div className="form-grid two"><label>Inspect portfolio<select value={evidence} onChange={e=>{setEvidence(e.target.value);setTrade("");}}>{Object.keys(audit.results).map(k=><option key={k} value={k}>{labels[k]||k}</option>)}</select></label><label>Inspect a trade<select value={trade} onChange={e=>setTrade(e.target.value)}><option value="">{row.trades.length?"Choose trade evidence":"No closed trades in this portfolio"}</option>{row.trades.map(t=><option key={t.id} value={t.id}>{t.id} · {t.token.slice(0,12)} · {usd(t.net_pnl_usd)}</option>)}</select></label></div>
    {selectedTrade&&<div className="trade-story"><div className="trade-story-heading"><h3>One modeled trade</h3><code>{selectedTrade.id}</code></div><div className="trade-story-grid"><div><span>Signal observed</span><b>{periodTime(selectedTrade.signal_ts)} UTC</b></div><div><span>Modeled entry</span><b>{periodTime(selectedTrade.entry_ts)} UTC</b></div><div><span>Modeled exit</span><b>{periodTime(selectedTrade.exit_ts)} UTC</b></div><div><span>Profit / loss before costs</span><b>{usd(selectedTrade.gross_pnl_usd)}</b></div><div><span>Total modeled costs</span><b>{usd(selectedTrade.costs_usd)}</b></div><div><span>Profit / loss after costs</span><b className={selectedTrade.net_pnl_usd<0?"negative":"positive"}>{usd(selectedTrade.net_pnl_usd)}</b></div></div><p className="fine-print">Token: <code>{selectedTrade.token}</code>. Exit reason: {selectedTrade.reason}. No transaction was submitted by this model.</p><details><summary>Exact trade record and cost components</summary><pre>{JSON.stringify(selectedTrade,null,2)}</pre></details></div>}
    <details><summary>Cost breakdown, warnings and missing-data flags</summary><pre>{JSON.stringify({costs:row.activity.cost_breakdown_usd,warnings:row.warnings,quality:audit.quality,failed:row.skipped},null,2)}</pre></details>
    <details><summary>Research limitations</summary><ul>{audit.limitations.map(f=><li key={f}>{f}</li>)}</ul></details>
  </section>;
}
