"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {FlaskConical,Play,Download,LockKeyhole,FileSearch,Check,ArrowRight,Database} from "lucide-react";
import {Badge,Notice,useWorkspace} from "./workspace";
import {browserMode} from "@/lib/api";
import type {Config,Segment,Quality} from "@/lib/types";
import * as experiments from "@/lib/experiments";
import type {Experiment} from "@/lib/experiments";
import {pct,usd,num,day} from "@/lib/format";
import Comparison from "./audit-comparison";
import AuditNextStep from "./audit-next-step";
import {auditGuide,type AuditAction} from "@/lib/audit-guide";
export type AuditSegment=Segment&{activity:{time_weighted_exposure_pct:number;round_trip_turnover_x:number;trade_count:number;signal_count:number;failed_execution_count:number;cost_breakdown_usd:Record<string,number>}};
export type AuditResult={phase:string;engine_version:string;dataset_kind:"REAL"|"SYNTHETIC";dataset_hash:string;fingerprint:string;quality:Quality;split:Record<string,number>;tokens:string[];benchmark_allocation_usd:number;benchmarks:Record<string,{name:string;rule:string;allocation:string}>;results:Record<string,AuditSegment>;findings:string[];limitations:string[]};
export {default as Comparison} from "./audit-comparison";
export default function Audit(){
  const {datasets,strategies}=useWorkspace();const [datasetId,setDatasetId]=useState(""),[c,setC]=useState<Config|null>(null),[tokens,setTokens]=useState<string[]>([]),[training,setTraining]=useState<AuditResult|null>(null),[holdout,setHoldout]=useState<AuditResult|null>(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(""),[attempts,setAttempts]=useState<Experiment[]>([]),[active,setActive]=useState<Experiment|null>(null),[offline,setOffline]=useState(false);
  const [operation,setOperation]=useState<AuditAction|null>(null),[exportPrepared,setExportPrepared]=useState(false);
  async function refreshAttempts(){setAttempts(await experiments.listExperiments());}
  useEffect(()=>{const local=browserMode&&localStorage.getItem("quant.audit.offline")==="true";experiments.setOfflineAudit(local);setOffline(local);void refreshAttempts().catch(e=>setError(e.message));},[]);
  async function storageMode(value:boolean){experiments.setOfflineAudit(value);setOffline(value);localStorage.setItem("quant.audit.offline",String(value));reset();setError("");await refreshAttempts().catch(e=>setError(e.message));}
  useEffect(()=>{if(!c&&strategies.length){const s=strategies.find(s=>s.id==="strategy-demo")||strategies[0];setC({...s.config});setDatasetId(s.dataset_id);setTokens(datasets.find(d=>d.id===s.dataset_id)?.tokens.map(t=>t.mint)||[]);}},[c,strategies,datasets]);
  const d=datasets.find(d=>d.id===datasetId);
  function reset(){setTraining(null);setHoldout(null);setActive(null);setExportPrepared(false);}
  function change(next:Config){setC(next);reset();}
  async function run(phase:"training"|"holdout"){if(!c||busy)return;setBusy(true);setOperation(phase);setProgress(0);setExportPrepared(false);setError("");try{const e=phase==="training"?await experiments.startExperiment(datasetId,c,tokens,setProgress):await experiments.evaluateExperiment(active!.id,setProgress);setActive(e);setTraining(e.training||null);setHoldout(e.holdout||null);}catch(e){setError(e instanceof Error?e.message:String(e));if(phase==="holdout"&&active)await experiments.getExperiment(active.id).then(setActive).catch(()=>undefined);}finally{setBusy(false);setOperation(null);await refreshAttempts().catch(()=>undefined);}}
  async function freeze(){if(!active||busy)return;setBusy(true);setOperation("freeze");setProgress(0);setError("");try{setActive(await experiments.freezeExperiment(active.id));await refreshAttempts();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);setOperation(null);}}
  async function restore(id:string){setError("");setExportPrepared(false);try{const e=await experiments.getExperiment(id);setActive(e);setDatasetId(e.manifest.dataset_id);setC(e.manifest.configuration);setTokens(e.manifest.token_universe);setTraining(e.training||null);setHoldout(e.holdout||null);}catch(e){setError(e instanceof Error?e.message:String(e));}}
  async function bundle(){if(!active||busy)return;setBusy(true);setOperation("export");setProgress(0);setError("");try{await experiments.exportExperiment(active,setProgress);setExportPrepared(true);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);setOperation(null);}}
  function evidence(phase:"training"|"holdout"){const target=document.getElementById(`${phase}-results`);target?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"});target?.focus({preventScroll:true});}
  function nextAction(action:AuditAction){if(action==="training"||action==="holdout")void run(action);else if(action==="freeze")void freeze();else void bundle();}
  if(!c||!d)return <Notice>Load a dataset and saved configuration to start an audit.</Notice>;
  const guideState={status:active?.status,training:!!training,holdout:!!holdout,frozen:!!active?.frozen_hash};
  const currentStep=auditGuide(guideState).step;
  const journey=[{title:"Data",detail:"Universe & quality"},{title:"Train",detail:"Inspect assumptions"},{title:"Freeze",detail:"Lock the snapshot"},{title:"Holdout",detail:"Compare after costs"},{title:"Export",detail:"Keep the evidence"}];
  return <><div className="page-heading audit-heading"><div><div className="eyebrow">FROM HYPOTHESIS TO EVIDENCE</div><h1>Put your hypothesis to the test.</h1><p>Does a wallet signal beat a comparable baseline after costs on a separate period?</p></div><div className="icon-box"><FlaskConical size={24}/></div></div>
    <ol className="audit-journey" aria-label="Audit workflow">{journey.map((step,index)=><li key={step.title} className={index<currentStep?"done":index===currentStep?"current":"pending"} aria-current={index===currentStep?"step":undefined}><span className="journey-number">{index<currentStep?<Check size={16}/>:String(index+1).padStart(2,"0")}</span><div><b>{step.title}</b><small>{step.detail}</small></div></li>)}</ol>
    {browserMode&&<label className="check-label"><input disabled={busy} type="checkbox" checked={offline} onChange={e=>void storageMode(e.target.checked)}/>Offline audit · keep this attempt and its lock on this device</label>}{offline&&<Notice>Device-only offline persistence. Local locks prevent accidental edits through this workflow; a user controlling browser storage can alter it. Server persistence and independent timestamp evidence are unavailable in this mode.</Notice>}
    {error&&<Notice error>{error}</Notice>}{d.kind==="SYNTHETIC"&&<Notice>SYNTHETIC example: every observation is simulated. You can learn the workflow without provider access. <Link className="text-link" href="/research/">Check access for a REAL study</Link></Notice>}
    <AuditNextStep state={guideState} busy={busy} progress={progress} operation={operation} disabled={!tokens.length} onAction={nextAction} onEvidence={evidence} exportPrepared={exportPrepared}/>
    <section className="audit-context" aria-label="Current research question"><div><span className="small-label">THE IDEA YOU ARE CHECKING</span><p>{c.hypothesis}</p></div><div className="context-data"><Badge kind={d.kind}/><b>{d.name}</b><span>{tokens.length} tokens · {c.wallet_ids.length||d.wallets.length} wallets · {usd(c.initial_capital_usd)} starting capital</span><span>Price / liquidity coverage: {num(d.quality.price_coverage_pct,1)}% / {num(d.quality.liquidity_coverage_pct,1)}%</span></div></section>
    <details className="audit-settings"><summary>Review or edit study setup <span>Universe, data quality, fees and dates</span></summary>
    <div className="audit-setup"><div className="audit-form"><section className="panel"><div className="panel-heading"><h2><span className="section-number">01</span>Hypothesis & universe</h2><Badge kind={d.kind}/></div><div className="form-grid two"><label>Dataset<select disabled={busy} value={datasetId} onChange={e=>{setDatasetId(e.target.value);setTokens(datasets.find(d=>d.id===e.target.value)?.tokens.map(t=>t.mint)||[]);reset();}}>{datasets.map(d=><option key={d.id} value={d.id}>{d.kind} · {d.name}</option>)}</select></label><label>Saved training configuration<select disabled={busy} value="" onChange={e=>{const s=strategies.find(s=>s.id===e.target.value);if(s)change({...s.config});}}><option value="">{c.name}</option>{strategies.filter(s=>s.dataset_id===datasetId).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><label className="hypothesis-field">Research hypothesis<textarea disabled={busy} rows={2} maxLength={4000} value={c.hypothesis} onChange={e=>change({...c,hypothesis:e.target.value})}/></label>
    <div className="wallet-grid audit-token-grid">{d.tokens.map(t=><label className={`check-label wallet-chip ${tokens.includes(t.mint)?"selected":""}`} key={t.mint}><input disabled={busy} type="checkbox" checked={tokens.includes(t.mint)} onChange={e=>{setTokens(e.target.checked?[...tokens,t.mint]:tokens.filter(x=>x!==t.mint));reset();}}/>{t.symbol}</label>)}</div><details><summary>Selected wallet universe · {c.wallet_ids.length||d.wallets.length} wallets</summary><div className="wallet-grid">{d.wallets.map(w=><label className="check-label mono" key={w} title={w}><input disabled={busy} type="checkbox" checked={!c.wallet_ids.length||c.wallet_ids.includes(w)} onChange={e=>{const selected=c.wallet_ids.length?c.wallet_ids:d.wallets,next=e.target.checked?[...selected,w]:selected.filter(x=>x!==w);if(!next.length){setError("Select at least one wallet in the research universe.");return;}change({...c,wallet_ids:next});}}/>{w.length>20?w.slice(0,8)+"…"+w.slice(-5):w}</label>)}</div></details><p className="fine-print">Token selection is fixed before each attempt, not ranked by future returns. Selecting a universe discovered from the full historical period can still introduce selection and survivorship bias.</p>
    <div className="quality-list"><div><span>Historical price / liquidity coverage</span><b>{num(d.quality.price_coverage_pct,1)}% / {num(d.quality.liquidity_coverage_pct,1)}%</b></div><div><span>Supported swaps / market observations</span><b>{d.quality.swap_events} / {d.quality.market_observations}</b></div><div className="dataset-hash"><span>Dataset content SHA-256</span><code>{d.content_hash}</code></div></div><details><summary>Provider provenance, coverage and exclusions</summary><pre>{JSON.stringify({quality:d.quality,provenance:d.provenance,limitations:d.limitations},null,2)}</pre></details><Link className="text-link" href="/research/">Create a genuine dataset</Link></section>
    <section className="panel"><div className="panel-heading"><h2><span className="section-number">02</span>Training configuration</h2><Link className="text-link" href="/lab/">All strategy controls</Link></div><div className="form-grid two">{([{key:"min_wallet_count",label:"Unique prior-qualified buyers",min:1,max:100,step:1},{key:"fee_bps",label:"DEX fee / side (bps)",min:0,max:1000,step:1},{key:"entry_delay_minutes",label:"Entry delay (minutes)",min:0,max:1440,step:1},{key:"slippage_bps",label:"Slippage / side (bps)",min:0,max:1000,step:1},{key:"train_fraction",label:"Chronological training fraction",min:.2,max:.8,step:.05},{key:"warmup_hours",label:"Prior evidence warmup (hours)",min:1,max:720,step:1}] as const).map(f=><label key={f.key}>{f.label}<input type="number" disabled={busy} min={f.min} max={f.max} step={f.step} value={c[f.key]} onChange={e=>change({...c,[f.key]:Number(e.target.value)})}/></label>)}</div><details><summary>Exact strategy and execution assumptions</summary><pre>{JSON.stringify(c,null,2)}</pre></details><div className="button-row"><button className="button primary" disabled={busy||!tokens.length} onClick={()=>void run("training")}><Play size={16}/>{busy?(progress?`Processing ${progress}%`:"Running this phase…"):"Inspect training vs benchmarks"}</button></div><p className="fine-print">Training can run even when later holdout observations are incomplete. Missing required observations in the evaluated period block performance.</p></section>
    </div><aside className="study-sheet"><div className="eyebrow">THE STUDY SHEET</div><div className="study-title"><Database size={19}/><h2>Your experiment, at a glance.</h2></div><div className="study-dataset"><Badge kind={d.kind}/><b>{d.name}</b><span>{day(d.start_ts)} – {day(d.end_ts)} · UTC</span></div>
      <div className="study-status"><LockKeyhole size={16}/><span>{active?.frozen_hash?"Snapshot frozen. Edits start a new attempt.":"Draft configuration. Inspect training before freezing."}</span></div>
      <div className="study-facts"><div><span>Starting capital</span><b>{usd(c.initial_capital_usd)}</b></div><div><span>Selected universe</span><b>{c.wallet_ids.length||d.wallets.length} wallets · {tokens.length} tokens</b></div><div><span>Position size</span><b>{usd(c.position_size_usd)}</b></div><div><span>DEX fee / side</span><b>{c.fee_bps} bps</b></div><div><span>Slippage / side</span><b>{c.slippage_bps} bps</b></div><div><span>Entry delay</span><b>{c.entry_delay_minutes} min</b></div><div><span>Holding interval</span><b>{c.holding_minutes} min</b></div></div>
      <div className="study-split"><div><span>Training <b>{num(c.train_fraction*100,0)}%</b></span><span>Holdout <b>{num((1-c.train_fraction)*100,0)}%</b></span></div><div className="split-track" aria-hidden="true"><i style={{width:`${Math.max(0,Math.min(100,c.train_fraction*100))}%`}}/><i/></div><p>Chronological split. Sensitivity uses training only.</p></div>
      <p className="study-warning">{d.kind==="SYNTHETIC"?"This is a simulated study, not evidence of real Solana performance.":"Missing required prices or liquidity block performance in the evaluated period."}</p><Link className="text-link" href="/datasets/">Inspect the source data <ArrowRight size={15}/></Link>
    </aside></div></details>
    {training&&<Comparison audit={training}/>}
    {active?.sensitivity&&<section className="panel"><h2>Training-only sensitivity · all seven rows</h2><p>{active.sensitivity.design.design} No best result is selected. Holdout is not used.</p><div className="table-wrap"><table><thead><tr><th>Pre-specified row</th><th>Changed control</th><th>Training gross</th><th>Training net</th><th>Trades</th></tr></thead><tbody>{active.sensitivity.rows.map(r=><tr key={r.row}><td>{r.row}</td><td>{JSON.stringify(r.changes)}</td><td>{pct(r.metrics.gross_return_pct)}</td><td>{pct(r.metrics.net_return_pct)}</td><td>{r.metrics.trade_count}</td></tr>)}</tbody></table></div></section>}
    {training&&active&&<section className="panel freeze-panel"><div className="panel-heading"><h2><span className="section-number">03</span>{active.frozen_hash?"This snapshot is locked":"Ready to freeze after reviewing training"}</h2><LockKeyhole size={20}/></div><Notice>Historical data may already be known to you. A holdout is not guaranteed unseen, and positive returns do not prove alpha.</Notice><p className="fine-print">Use the next-step button above when ready. A parameter change creates a new attempt. Every failed and repeated attempt stays in the log. The legacy Strategy lab permits unrestricted exploration and cannot certify an unseen holdout.</p><details><summary>Immutable experiment manifest · {active.id}</summary><pre>{JSON.stringify({manifest_hash:active.manifest_hash,frozen_hash:active.frozen_hash,history:active.history,manifest:active.manifest},null,2)}</pre></details></section>}
    {holdout&&<Comparison audit={holdout}/>}{active?.frozen_hash&&<section className="panel export-panel"><div className="export-icon" aria-hidden="true"><Download size={27}/></div><div><div className="eyebrow">A RESULT YOU CAN RERUN</div><h2>Keep the evidence.</h2><p>Manifest, original dataset when permitted, exact engine source, results, trades, exclusions and report. Unzip and run <code>python3 reproduce.py</code>. No keys or wallet session data.</p><div className="button-row"><button className="button primary" disabled={busy} onClick={()=>void bundle()}><Download size={16}/>Download reproduction ZIP</button></div></div></section>}
    <section className="panel attempt-log" id="audit-attempt-log"><h2>All experiment attempts · {attempts.length}</h2><p>Configuration snapshots cannot be edited. Repeated trials on the same holdout are correlated and do not create fresh evidence. Online hosted manifests and lifecycle hashes persist on the server; hosted details and offline locks stay on this device.</p><div className="audit-attempts">{attempts.map(e=><div className="audit-attempt" key={e.id}><div><b>{e.manifest.configuration.name}</b><small className="mono">{e.id} · {e.status} · {e.created_at}</small>{e.error&&<p>{e.error}</p>}{["training","evaluating"].includes(e.status)&&<small>Running or interrupted browser run. The attempt remains visible.</small>}</div><button className="button" disabled={busy} onClick={()=>void restore(e.id)}>Inspect attempt</button></div>)}</div></section>
  </>;
}
