"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {Radio,Square,LoaderCircle} from "lucide-react";
import {chainRequest,LiveStatus,walletHistory,mergeHistory,RawHistory,TokenMarket,shortAddress} from "@/lib/chain";
import {Detections,AccumulationEvent} from "@/lib/research";
import {researchCompute} from "@/lib/api";
import {Badge,Empty,Notice} from "./workspace";
import {useWallet} from "./wallet-provider";
import {money,utc} from "./chain-chart";
type Shown=AccumulationEvent&{market:TokenMarket|null};
export default function LiveSignals(){
  const wallet=useWallet();const [addresses,setAddresses]=useState(""),[score,setScore]=useState(0),[minimum,setMinimum]=useState(3),[window,setWindow]=useState(30),[liquidity,setLiquidity]=useState(100000),[sample,setSample]=useState(10),[tradeSize,setTradeSize]=useState(0),[hold,setHold]=useState(120),[status,setStatus]=useState<LiveStatus|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[running,setRunning]=useState(false),[fetching,setFetching]=useState(false),[events,setEvents]=useState<Shown[]>([]),[swaps,setSwaps]=useState(0),[lastPoll,setLastPoll]=useState<number|null>(null),[limitations,setLimitations]=useState<string[]>([]);
  const version=useRef(0),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  useEffect(()=>{chainRequest<LiveStatus>("/api/live/status").then(setStatus).catch(e=>setError(String(e.message)));return()=>{version.current++;if(timer.current)clearTimeout(timer.current);};},[]);
  function stop(){version.current++;if(timer.current)clearTimeout(timer.current);timer.current=null;setRunning(false);setFetching(false);setMessage("Monitoring stopped.");}
  async function start(e:React.FormEvent){e.preventDefault();const wallets=[...new Set(addresses.split(/[\s,]+/).filter(Boolean))];if(wallets.length<minimum||wallets.length>5){setError("Enter enough wallets for the selected minimum (maximum 5 addresses).");return;}setError("");setEvents([]);setRunning(true);const current=++version.current;
    const historyCache=new Map<string,RawHistory>();let lastSweep=0;
    async function poll(){if(current!==version.current)return;if(document.visibilityState!=="visible"){timer.current=setTimeout(()=>void poll(),75000);return;}setFetching(true);let delay=75000;
      try{const end=Math.floor(Date.now()/1000),start=end-7*86400,histories:RawHistory[]=[];
        const fullSweep=end-lastSweep>=900;
        for(let i=0;i<wallets.length;i++){if(current!==version.current)return;const previous=historyCache.get(wallets[i]);setMessage(`Wallet ${i+1}/${wallets.length}: reading ${previous&&!fullSweep?"new finalized events":"score history"}…`);const update=await walletHistory(wallets[i],previous&&!fullSweep?Math.max(start,previous.requested_end-300):start,end,previous&&!fullSweep?3:10);const history=previous&&!fullSweep?mergeHistory(previous,update,start,end):update;historyCache.set(wallets[i],history);histories.push(history);}
        if(fullSweep)lastSweep=end;
        const detected=await researchCompute<Detections>("accumulation",{histories,config:{min_wallet_count:minimum,accumulation_minutes:window,min_wallet_return_pct:score,min_closed_trades:sample,min_trade_size_usd:tradeSize,holding_minutes:hold,min_liquidity_usd:liquidity}});
        const recent=detected.events.filter(s=>s.ts>=end-window*60).slice(-5),shown:Shown[]=[];
        for(const signal of recent){let market:TokenMarket|null=null;try{market=await chainRequest<TokenMarket>(`/api/markets/${signal.token}`,{ttl:60});}catch{/* Missing liquidity cannot qualify a positive depth filter. */}if(liquidity>0&&(market?.liquidity_usd==null||market.liquidity_usd<liquidity))continue;shown.push({...signal,market});}
        if(current!==version.current)return;setError("");setEvents(shown.reverse());setSwaps(detected.observed_swaps);setLastPoll(end);setLimitations(detected.limitations);setMessage(shown.length?"Recent multi-wallet research events observed.":"No recent event met the prior-evidence and current-liquidity thresholds.");
      }catch(e){if(current!==version.current)return;setError(e instanceof Error?e.message:String(e));delay=150000;setMessage("The provider did not return a usable sample. Monitoring will retry with backoff.");}
      finally{if(current===version.current){setFetching(false);timer.current=setTimeout(()=>void poll(),delay);}}
    }void poll();
  }
  return <><div className="page-heading"><div><div className="eyebrow">NEAR-REAL-TIME RESEARCH</div><h1>Live accumulation signals</h1><p>Observe qualified wallet clusters. Evaluate the hypothesis before drawing conclusions.</p></div><Badge kind="REAL"/></div>
    {status&&!status.helius&&<Notice>Decoded on-chain monitoring requires Helius access on the server. No synthetic signals are shown when the provider is unavailable.</Notice>}
    {error&&<Notice error>{error}</Notice>}{message&&<div className="notice neutral" role="status">{fetching&&<LoaderCircle size={17} className="spin"/>}{message}</div>}
    <section className="panel"><form onSubmit={start}><label>Wallet universe<textarea required rows={3} maxLength={240} disabled={running} value={addresses} onChange={e=>setAddresses(e.target.value)} placeholder="At most 5 public wallet addresses"/></label>{wallet.address&&!running&&<button type="button" className="text-link" onClick={()=>setAddresses(s=>s?s+"\n"+wallet.address:wallet.address!)}>Add connected wallet</button>}<div className="form-grid live-parameters">{[
      ["Prior average quote return (%)",score,setScore,-100,10000], ["Minimum unique wallets",minimum,setMinimum,2,5], ["Accumulation window (minutes)",window,setWindow,1,1440], ["Current pool liquidity minimum (USD)",liquidity,setLiquidity,0,1e12], ["Minimum prior fully matched sales",sample,setSample,10,1000], ["Minimum buy size (USD)",tradeSize,setTradeSize,0,1e12], ["Research holding period (minutes)",hold,setHold,1,10080]
    ].map(([label,value,set,min,max])=><label key={String(label)}>{String(label)}<input type="number" required disabled={running} value={Number(value)} min={Number(min)} max={Number(max)} step={String(label).includes("return")?"any":1} onChange={e=>(set as (v:number)=>void)(Number(e.target.value))}/></label>)}</div><div className="button-row"><button className="button primary" type="submit" disabled={running}><Radio size={16}/>Start monitoring</button>{running&&<button className="button" type="button" onClick={stop}><Square size={15}/>Stop</button>}</div></form><p className="fine-print">Polls every 75 seconds while visible; errors back off. Initial score history covers 7 days and up to 1,000 transactions per wallet. Updates fetch at most 3 pages with a five-minute overlap; a full refresh runs every 15 minutes. Positive USD trade-size filters cannot qualify swaps without historical USD valuations.</p></section>
    <div className="stat-grid"><div className="stat"><span>Monitoring state</span><strong className="compact-stat">{running?fetching?"Reading":"Monitoring":"Stopped"}</strong><small>Finalized mainnet transactions</small></div><div className="stat"><span>Observed supported swaps</span><strong>{swaps}</strong><small>Fetched score-history sample</small></div><div className="stat"><span>Recent qualifying events</span><strong>{events.length}</strong><small>Within the selected accumulation window</small></div><div className="stat"><span>Last successful poll</span><strong className="compact-stat">{lastPoll?new Date(lastPoll*1000).toISOString().slice(11,19):"N/A"}</strong><small>UTC · missing requests do not update this time</small></div></div>
    {events.length?events.map(s=><section className="panel signal-card" key={s.token+":"+s.ts}><div className="panel-heading"><h2>New on-chain research event</h2><span className="tag">{utc(s.ts)}</span></div><div className="quality-list"><div><span>Token</span><Link href={`/markets/?mint=${s.token}`} className="text-link">{s.market?.symbol||shortAddress(s.token)}</Link></div><div><span>Eligible wallets detected</span><b>{s.wallet_count}</b></div><div><span>Observed accumulation interval</span><b>{Math.floor(s.window_seconds/60)}m {s.window_seconds%60}s</b></div><div><span>Earlier similar detections in this sample</span><b>{s.prior_similar_events}</b></div><div><span>Current pool liquidity (polling time)</span><b>{money(s.market?.liquidity_usd)}</b></div><div><span>Proposed research holding period</span><b>{hold} min</b></div></div><div className="tag-row">{s.wallets.map(w=><span className="tag mono" key={w} title={w}>{shortAddress(w)}</span>)}</div><Notice>Price outcomes and historical liquidity must be retrieved before evaluating this event. No entry or exit transaction is submitted.</Notice></section>):<Empty title={running?"No qualifying event observed":"Choose wallets and start monitoring"}>{running?"Insufficient prior evidence, incomplete coverage or failing thresholds can produce zero events.":"Detections use prior matched-sale evidence and unique buyers in a rolling window."}</Empty>}
    <section className="panel"><h2>Research limits</h2><ul>{[...limitations,"The liquidity filter uses a current pool observation at polling time. It does not validate liquidity at the historical event timestamp.","The holding-period control records the research horizon. Real outcomes are evaluated in Strategy lab using complete historical data."].map(l=><li key={l}>{l}</li>)}</ul><Link className="button" href="/research/">Build a historical wallet study</Link></section>
  </>;
}
