"use client";
import {useEffect,useState} from "react";
import {Search,RefreshCw,LoaderCircle,ExternalLink} from "lucide-react";
import {chainRequest,PriceHistory,SOL_MINT,TokenMarket,shortAddress} from "@/lib/chain";
import {Badge,Empty,Notice} from "./workspace";
import {RealChart,money,quantity,change,utc} from "./chain-chart";
import MarketUnavailable from "./market-unavailable";
export default function Markets(){
  const [mint,setMint]=useState(SOL_MINT),[days,setDays]=useState(7),[query,setQuery]=useState(""),[results,setResults]=useState<TokenMarket[]>([]),[market,setMarket]=useState<TokenMarket|null>(null),[history,setHistory]=useState<PriceHistory|null>(null),[error,setError]=useState(""),[historyError,setHistoryError]=useState(""),[searchError,setSearchError]=useState(""),[searching,setSearching]=useState(false),[loading,setLoading]=useState(false),[reload,setReload]=useState(0);
  useEffect(()=>{const m=new URLSearchParams(window.location.search).get("mint");if(m&&/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(m))setMint(m);},[]);
  useEffect(()=>{let alive=true;setMarket(null);setHistory(null);setError("");setHistoryError("");setLoading(true);void Promise.allSettled([chainRequest<TokenMarket>(mint===SOL_MINT?"/api/markets/sol":`/api/markets/${mint}`),chainRequest<PriceHistory>(`/api/markets/${mint}/history?days=${days}`)]).then(([m,h])=>{if(!alive)return;if(m.status==="fulfilled")setMarket(m.value);else setError(String(m.reason.message));if(h.status==="fulfilled")setHistory(h.value);else setHistoryError(String(h.reason.message));setLoading(false);});return()=>{alive=false;};},[mint,days,reload]);
  async function search(e:React.FormEvent){e.preventDefault();setSearching(true);setSearchError("");try{setResults(await chainRequest<TokenMarket[]>("/api/markets/search?q="+encodeURIComponent(query),{ttl:60}));}catch(e){setSearchError(e instanceof Error?e.message:String(e));}finally{setSearching(false);}}
  return <><div className="page-heading"><div><div className="eyebrow">SOLANA MARKET OBSERVATIONS</div><h1>Markets</h1><p>Provider prices, token mints and historical observations.</p></div><div className="button-row"><Badge kind="REAL"/><button className="button" disabled={loading} onClick={()=>setReload(reload+1)}><RefreshCw size={16}/>Refresh</button></div></div>
    <section className="panel"><form className="inline-form" onSubmit={search}><label className="grow">Find a Solana token<input required maxLength={80} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Symbol, name or token mint"/></label><button className="button" disabled={searching} type="submit">{searching?<LoaderCircle size={16} className="spin"/>:<Search size={16}/>}Search</button><button className="button" type="button" onClick={()=>{setMint(SOL_MINT);setResults([]);}}>SOL</button></form>{searchError&&<Notice error>{searchError}</Notice>}{results.length>0&&<div className="token-search-list">{results.map(t=><button className="token-search-row" key={t.mint} onClick={()=>{setMint(t.mint);setResults([]);}}><b>{t.symbol||"N/A"}</b><span>{t.name||"N/A"}</span><code title={t.mint}>{shortAddress(t.mint)}</code><span>{money(t.price_usd,6)}</span></button>)}</div>}{!searching&&query&&!results.length&&searchError===""&&<p className="fine-print">Search results use on-chain mint addresses. Symbols alone do not establish token identity.</p>}</section>
    {error&&<MarketUnavailable message={error} busy={loading} onRetry={()=>setReload(n=>n+1)}/>}{loading&&<div className="notice neutral" role="status"><LoaderCircle size={17} className="spin"/>Retrieving real market data…</div>}
    {market&&<><div className="market-title"><div><h2>{market.name||"Unknown token"} <span className="tag">{market.symbol||"N/A"}</span></h2><code className="mint-address">{mint}</code></div><a className="text-link" href={`https://solscan.io/token/${mint}`} target="_blank" rel="noopener noreferrer"><ExternalLink size={15}/>Token explorer</a></div><div className="stat-grid"><div className="stat"><span>Current price</span><strong>{money(market.price_usd,market.price_usd!=null&&market.price_usd<1?8:2)}</strong><small>{market.provider}</small></div><div className="stat"><span>24h change</span><strong className={(market.change_24h_pct||0)<0?"negative":"positive"}>{change(market.change_24h_pct)}</strong><small>Provider-reported change</small></div><div className="stat"><span>24h volume</span><strong>{money(market.volume_24h_usd,0)}</strong><small>{market.dex?"Selected pool":"Aggregated market"}</small></div><div className="stat"><span>Liquidity</span><strong>{money(market.liquidity_usd,0)}</strong><small>{market.dex?market.dex+" pool":"Unavailable from this endpoint"}</small></div></div></>}
    <section className="panel"><div className="panel-heading"><div><h2>{market?.symbol||(mint===SOL_MINT?"SOL":shortAddress(mint))} price history</h2><p>{history?`${history.provider} · ${history.points.length} real observations · UTC`:"Historical provider observations"}</p></div><div className="segmented">{[1,7,30].map(d=><button key={d} className={days===d?"selected":""} onClick={()=>setDays(d)}>{d}D</button>)}</div></div>{historyError?<MarketUnavailable message={historyError} history busy={loading} onRetry={!error?()=>setReload(n=>n+1):undefined}/>:history?<RealChart points={history.points} resolution={history.resolution_seconds}/>:!loading?<Empty title="No price history">Historical data has not been returned.</Empty>:null}{history?.limitations.map(x=><p className="fine-print" key={x}>{x}</p>)}</section>
    {market&&<section className="panel"><div className="panel-heading"><h2>Market provenance</h2><span className="tag">{market.provider}</span></div><dl className="provenance-list"><div><dt>Market cap</dt><dd>{money(market.market_cap_usd,0)}</dd></div><div><dt>FDV</dt><dd>{money(market.fdv_usd,0)}</dd></div><div><dt>Pair</dt><dd className="mono">{market.pair_address||"N/A"}</dd></div><div><dt>Retrieved</dt><dd>{utc(Date.parse(market.retrieved_at)/1000)}</dd></div></dl><ul>{market.limitations.map(x=><li key={x}>{x}</li>)}</ul></section>}
  </>;
}
