"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import Link from "next/link";
import {Wallet as WalletIcon,RefreshCw,ExternalLink,ShieldCheck,LoaderCircle,Eye,Copy} from "lucide-react";
import {Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {useWallet} from "./wallet-provider";
import {Badge,Empty,Notice} from "./workspace";
import {chainRequest,WalletSnapshot,Transactions,PortfolioHistory,shortAddress} from "@/lib/chain";
import {RealChart,money,quantity,utc} from "./chain-chart";
export default function Wallet(){
  const connected=useWallet();const [watch,setWatch]=useState(""),[studied,setStudied]=useState(""),[data,setData]=useState<WalletSnapshot|null>(null),[tx,setTx]=useState<Transactions|null>(null),[history,setHistory]=useState<PortfolioHistory|null>(null),[error,setError]=useState(""),[txError,setTxError]=useState(""),[historyError,setHistoryError]=useState(""),[loading,setLoading]=useState(false),[pageBusy,setPageBusy]=useState(false),[copyMessage,setCopyMessage]=useState("");
  const wallet=studied||connected.address;
  const walletRef=useRef(wallet);walletRef.current=wallet;
  const isOwned=!!wallet&&connected.session?.wallet===wallet;
  const load=useCallback(async()=>{
    if(!wallet)return;setLoading(true);setError("");setTxError("");
    const [snapshot,transactions]=await Promise.allSettled([chainRequest<WalletSnapshot>(`/api/wallets/${encodeURIComponent(wallet)}`),chainRequest<Transactions>(`/api/wallets/${encodeURIComponent(wallet)}/transactions`)]);
    if(walletRef.current!==wallet)return;
    if(snapshot.status==="fulfilled")setData(snapshot.value);else setError(String(snapshot.reason.message));
    if(transactions.status==="fulfilled")setTx(transactions.value);else setTxError(String(transactions.reason.message));setLoading(false);
  },[wallet]);
  useEffect(()=>{let alive=true;setData(null);setTx(null);setHistory(null);setError("");setTxError("");setHistoryError("");setPageBusy(false);setLoading(false);if(!wallet)return;setLoading(true);void Promise.allSettled([chainRequest<WalletSnapshot>(`/api/wallets/${encodeURIComponent(wallet)}`),chainRequest<Transactions>(`/api/wallets/${encodeURIComponent(wallet)}/transactions`)]).then(([d,t])=>{if(!alive)return;if(d.status==="fulfilled")setData(d.value);else setError(String(d.reason.message));if(t.status==="fulfilled")setTx(t.value);else setTxError(String(t.reason.message));setLoading(false);});return()=>{alive=false;};},[wallet]);
  useEffect(()=>{if(!wallet||!isOwned){setHistory(null);return;}let alive=true;const observe=async()=>{try{await chainRequest(`/api/wallets/${wallet}/observations`,{body:{}});const h=await chainRequest<PortfolioHistory>(`/api/wallets/${wallet}/observations`);if(alive){setHistory(h);setHistoryError("");}}catch(e){if(alive)setHistoryError(e instanceof Error?e.message:String(e));}};void observe();const timer=setInterval(()=>{if(document.visibilityState==="visible")void observe();},60000);return()=>{alive=false;clearInterval(timer);};},[wallet,isOwned]);
  async function next(){if(!wallet||!tx?.next_cursor)return;setPageBusy(true);try{const r=await chainRequest<Transactions>(`/api/wallets/${wallet}/transactions?before=${tx.next_cursor}`);if(walletRef.current!==wallet)return;setTx(current=>current?{...r,transactions:[...new Map([...current.transactions,...r.transactions].map(t=>[t.signature,t])).values()]}:r);}catch(e){if(walletRef.current===wallet)setTxError(e instanceof Error?e.message:String(e));}finally{if(walletRef.current===wallet)setPageBusy(false);}}
  const activity=new Map<number,number>();for(const t of tx?.transactions||[])if(t.ts!=null){const day=Math.floor(t.ts/86400)*86400;activity.set(day,(activity.get(day)||0)+1);}const activityRows=[...activity].sort((a,b)=>a[0]-b[0]).map(([ts,count])=>({ts,count}));
  return <><div className="page-heading"><div><div className="eyebrow">READ-ONLY MAINNET OBSERVATIONS</div><h1>Wallet</h1><p>Balances, recent activity and saved portfolio observations.</p></div><div className="button-row"><Badge kind="REAL"/>{wallet&&<button className="button" disabled={loading} onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button>}</div></div>
    <section className="panel"><form className="inline-form" onSubmit={e=>{e.preventDefault();setStudied(watch.trim());}}><label className="grow">Research a public wallet address<input value={watch} onChange={e=>setWatch(e.target.value)} required maxLength={44} placeholder="Solana public address"/></label><button className="button" type="submit"><Eye size={16}/>Inspect</button>{connected.address&&<button className="button" type="button" onClick={()=>{setStudied("");setWatch("");}}>My wallet</button>}</form></section>
    {!wallet?<Empty title="Connect Phantom or inspect a public wallet">Use Connect Wallet above, or enter a public address to read mainnet data.</Empty>:<>
    <section className="panel wallet-identity"><div><span className="small-label">{connected.address===wallet?"CONNECTED WALLET":"PUBLIC WALLET · WATCH ONLY"}</span><code className="mint-address">{wallet}</code><div className="tag-row"><span className="tag">mainnet-beta</span>{isOwned&&<span className="tag mint"><ShieldCheck size={14}/>Signature verified</span>}</div></div><div className="button-row"><button className="button small" onClick={()=>void navigator.clipboard.writeText(wallet).then(()=>setCopyMessage("Address copied.")).catch(()=>setCopyMessage("Copy unavailable. Select the address above."))}><Copy size={14}/>Copy</button><a className="text-link" href={`https://explorer.solana.com/address/${encodeURIComponent(wallet)}?cluster=mainnet-beta`} target="_blank" rel="noopener noreferrer"><ExternalLink size={15}/>Explorer</a></div></section>{copyMessage&&<p className="fine-print" role="status">{copyMessage}</p>}
    {connected.address===wallet&&!isOwned&&<div className="notice neutral"><ShieldCheck size={17}/><div>Sign a login message to save portfolio observations across visits. Public balances remain readable without signing.<button className="button small" disabled={connected.signing} onClick={()=>void connected.login()}>{connected.signing?"Waiting for Phantom…":"Sign in with Phantom"}</button></div></div>}
    {error&&<Notice error>{error}</Notice>}{loading&&<div className="notice neutral" role="status"><LoaderCircle size={17} className="spin"/>Reading Solana mainnet…</div>}
    {data&&<><div className="stat-grid"><div className="stat"><span>SOL balance</span><strong>{quantity(data.sol_balance,9)}</strong><small>{data.balance_lamports.toLocaleString()} lamports</small></div><div className="stat"><span>SOL value</span><strong>{money(data.sol_value_usd)}</strong><small>{money(data.sol_price_usd)} / SOL</small></div><div className="stat"><span>{data.portfolio_complete?"Estimated portfolio value":"Valued subtotal · partial"}</span><strong>{money(data.valued_subtotal_usd)}</strong><small>{data.unpriced_tokens} unpriced token holdings</small></div><div className="stat"><span>Positive token holdings</span><strong>{data.tokens.length}</strong><small>Standard SPL + Token-2022</small></div></div>{data.warnings.map(x=><Notice key={x}>{x}</Notice>)}
    <section className="panel"><div className="panel-heading"><h2>Token balances</h2><span className="tag">Observed {utc(Date.parse(data.retrieved_at)/1000)}</span></div>{data.tokens.length?<div className="table-wrap"><table><thead><tr><th>Token / mint</th><th>Amount</th><th>USD price</th><th>Estimated value</th><th>Data</th></tr></thead><tbody>{data.tokens.map(t=><tr key={t.mint}><td><b>{t.symbol||"N/A"}</b><small className="mono" title={t.mint}>{shortAddress(t.mint)}</small></td><td title={`Raw amount: ${t.raw_amount} · decimals: ${t.decimals}`}>{t.amount}</td><td>{money(t.price_usd,8)}</td><td>{money(t.value_usd)}</td><td>{!t.valuation_supported?"Extension requires normalization":t.price_usd==null?"Price unavailable":<Link className="text-link" href={`/markets/?mint=${t.mint}`}>Market</Link>}</td></tr>)}</tbody></table></div>:<p className="body-small">No positive token balances were returned.</p>}<ul>{data.limitations.map(x=><li key={x}>{x}</li>)}</ul></section></>}
    <section className="panel"><div className="panel-heading"><div><h2>Portfolio value over time</h2><p>Recorded observations from this app. No invented past balances.</p></div><Badge kind="REAL"/></div>{historyError&&<Notice error>{historyError}</Notice>}{history?<><RealChart points={history.points} field="valued_usd" label="Observed valued subtotal"/>{history.points.some(p=>!p.complete)&&<Notice>Some observations exclude unpriced tokens. This series shows valued subtotal, not complete portfolio performance.</Notice>}</>:<Empty title={isOwned?"Waiting for observations":"Sign in to save observations"}>{isOwned?"A new observation is saved at most once a minute while this page is open.":"Use your connected Phantom account and sign a login message. Historical holdings cannot be reconstructed from current balances."}</Empty>}</section>
    <section className="panel"><div className="panel-heading"><h2>Observed wallet activity</h2><span className="tag">{tx?.transactions.length||0} fetched signatures</span></div>{activityRows.length?<div className="chart short"><ResponsiveContainer width="100%" height="100%"><BarChart data={activityRows}><CartesianGrid stroke="#262c38" vertical={false}/><XAxis dataKey="ts" tickFormatter={v=>new Date(v*1000).toLocaleDateString("en-GB",{timeZone:"UTC"})} tick={{fill:"#929cae",fontSize:12}}/><YAxis allowDecimals={false} tick={{fill:"#929cae",fontSize:12}}/><Tooltip labelFormatter={v=>utc(Number(v))} contentStyle={{background:"#171c27",border:"1px solid #323a49"}}/><Bar dataKey="count" name="Observed transactions" fill="#ada1f4" isAnimationActive={false}/></BarChart></ResponsiveContainer></div>:<p className="body-small">No timestamped activity was returned.</p>}<p className="fine-print">Counts cover fetched signatures only, not full lifetime activity.</p></section>
    <section className="panel"><div className="panel-heading"><h2>Recent transactions</h2><Link className="text-link" href={`/research/?wallet=${encodeURIComponent(wallet)}`}>Research this wallet</Link></div>{txError&&<Notice error>{txError}</Notice>}{tx?.warning&&<Notice>{tx.warning}</Notice>}{tx?.transactions.length?<div className="table-wrap"><table><thead><tr><th>Signature</th><th>Timestamp</th><th>Type</th><th>Status</th><th>Network fee (SOL)</th><th>Explorer</th></tr></thead><tbody>{tx.transactions.map(t=><tr key={t.signature}><td className="mono" title={t.signature}>{shortAddress(t.signature)}</td><td>{utc(t.ts)}</td><td>{t.type||"N/A"}</td><td>{t.status}</td><td>{quantity(t.fee_sol,9)}</td><td><a className="text-link" href={t.explorer_url} target="_blank" rel="noopener noreferrer">Explorer</a> · <a className="text-link" href={t.solscan_url} target="_blank" rel="noopener noreferrer">Solscan</a></td></tr>)}</tbody></table></div>:!loading&&<p className="body-small">No transaction history was returned.</p>}{tx?.next_cursor&&<button className="button" disabled={pageBusy} onClick={()=>void next()}>{pageBusy?"Reading older activity…":"Load older transactions"}</button>}<p className="fine-print">Network fee includes the RPC-reported transaction fee. Unknown DEX fees remain unavailable; transfers are not classified as swaps.</p></section></>}
  </>;
}
