"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {Search,Database,LoaderCircle,Download} from "lucide-react";
import {chainRequest,LiveStatus,RawHistory,walletHistory,shortAddress} from "@/lib/chain";
import {Analysis,analyze,importStudy,StudyBudget} from "@/lib/research";
import {download} from "@/lib/api";
import {useWallet} from "./wallet-provider";
import {Badge,Notice,useWorkspace} from "./workspace";
import {quantity,change,money,utc} from "./chain-chart";
import type {Dataset} from "@/lib/types";
export default function WalletResearch(){
  const wallet=useWallet(),workspace=useWorkspace();const [addresses,setAddresses]=useState(""),[hours,setHours]=useState(72),[sample,setSample]=useState(10),[status,setStatus]=useState<LiveStatus|null>(null),[analysis,setAnalysis]=useState<Analysis|null>(null),[histories,setHistories]=useState<RawHistory[]>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[includeMarkets,setIncludeMarkets]=useState(false),[saved,setSaved]=useState<Dataset|null>(null);
  const controller=useRef<AbortController|null>(null),budgetRef=useRef<StudyBudget|null>(null);const [requestLimit,setRequestLimit]=useState(240),[readiness,setReadiness]=useState<{ready:boolean;checks:{endpoint:string;status:string;message:string}[]}|null>(null);
  useEffect(()=>()=>controller.current?.abort(),[]);
  async function checkProviders(){setError("");try{setReadiness(await chainRequest("/api/providers/readiness",{body:{}}));}catch(e){setError(e instanceof Error?e.message:String(e));}}
  useEffect(()=>{const address=new URLSearchParams(window.location.search).get("wallet");if(address)setAddresses(address);chainRequest<LiveStatus>("/api/live/status").then(r=>{setStatus(r);setIncludeMarkets(r.birdeye);}).catch(e=>setError(String(e.message)));},[]);
  async function observe(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setSaved(null);setAnalysis(null);setHistories([]);try{
    const wallets=[...new Set(addresses.split(/[\s,]+/).filter(Boolean))];if(!wallets.length||wallets.length>5)throw new Error("Enter one to five unique Solana wallet addresses.");
    controller.current=new AbortController();budgetRef.current=new StudyBudget(requestLimit,controller.current.signal);
    const end=Math.floor(Date.now()/1000/300)*300,start=end-hours*3600,records:RawHistory[]=[];
    for(let i=0;i<wallets.length;i++){setMessage(`Wallet ${i+1}/${wallets.length}: requesting decoded history…`);records.push(await walletHistory(wallets[i],start,end,20,page=>setMessage(`Wallet ${i+1}/${wallets.length} · page ${page}/20 · budget ≤${budgetRef.current!.usedUpperBound}/${requestLimit}`),{signal:controller.current.signal,beforeRequest:budgetRef.current.beforeRequest}));}
    setMessage("Computing observed FIFO matches without using future wallet scores…");setHistories(records);setAnalysis(await analyze(records,sample));setMessage("Observed history analyzed. Review sample size and coverage before creating a dataset.");
  }catch(e){setError(e instanceof Error?e.message:String(e));setMessage("");}finally{setBusy(false);}}
  async function save(){setBusy(true);setError("");try{controller.current=new AbortController();const prior=budgetRef.current?.usedUpperBound||0;budgetRef.current=new StudyBudget(requestLimit,controller.current.signal);budgetRef.current.usedUpperBound=prior;const d=await importStudy(histories,includeMarkets,setMessage,budgetRef.current);setSaved(d);await workspace.refresh();setMessage(d.quality.performance_ready?"REAL dataset is ready. Select it in Audit this hypothesis to test the hypothesis.":"REAL dataset saved with missing-data flags. Unsupported performance calculations are blocked.");}catch(e){setError(e instanceof Error?e.message:String(e));setMessage("");}finally{setBusy(false);}}
  return <><div className="page-heading"><div><div className="eyebrow">OBSERVED WALLET EVIDENCE</div><h1>Wallet research</h1><p>Decode swaps, inspect matched-lot evidence and build a reproducible dataset.</p></div><Badge kind="REAL"/></div>
    {status&&!status.helius&&<Notice>Historical swap decoding requires a Helius key on the server. Mainnet wallet balances and market pages remain available. No synthetic history is substituted.</Notice>}
    <section className="panel"><div className="panel-heading"><h2>Provider readiness</h2><button className="button" disabled={busy} onClick={()=>void checkProviders()}>Check endpoint access</button></div><p>Keys remain on the server. This check uses at most six provider attempts and verifies endpoint access, not full study coverage.</p>{readiness&&<><Notice error={!readiness.ready}>{readiness.ready?"Endpoints accessible. Coverage still requires validation.":"REAL study blocked. Configure authorized server keys and endpoint plan access."}</Notice><ul>{readiness.checks.map(c=><li key={c.endpoint}>{c.endpoint}: {c.status} · {c.message}</li>)}</ul></>}</section>
    {error&&<Notice error>{error}</Notice>}{message&&<div className="notice neutral" role="status">{busy&&<LoaderCircle size={17} className="spin"/>}{message}</div>}
    <section className="panel"><form onSubmit={observe}><label>Research wallet universe<textarea required rows={3} maxLength={240} value={addresses} onChange={e=>setAddresses(e.target.value)} placeholder="One public wallet address per line (maximum 5)"/></label>{wallet.address&&<button className="text-link" type="button" onClick={()=>setAddresses(wallet.address!)}>Use connected wallet</button>}<div className="form-grid two"><label>Historical lookback<select value={hours} onChange={e=>setHours(Number(e.target.value))}>{[24,72,168,336].map(h=><option key={h} value={h}>{h/24} days · UTC · 5-minute boundary</option>)}</select></label><label>Minimum evidence sample<input type="number" min={10} max={1000} required value={sample} onChange={e=>setSample(Number(e.target.value))}/><small>Fully matched sale observations; this is not a profitability guarantee.</small></label></div><label>Maximum provider attempts, including retries<input type="number" min={6} max={1500} value={requestLimit} onChange={e=>setRequestLimit(Number(e.target.value))}/><small>Two attempts reserved per hosted request. Changing this limit requires your explicit input.</small></label><div className="button-row">{busy&&<button className="button" type="button" onClick={()=>{controller.current?.abort();setMessage("Cancelling; no partial dataset will be published.");}}>Cancel</button>}<button className="button primary" disabled={busy} type="submit"><Search size={16}/>{busy?"Reading historical evidence…":"Analyze history"}</button>{analysis&&<button className="button" type="button" onClick={()=>download("REAL_wallet_observations.json",analysis)}><Download size={16}/>Export evidence</button>}</div></form></section>
    {analysis&&<><div className="notice neutral">Return statistics below use actual quote units before costs. Observed matched PnL is reported separately in SOL, USDC and USDT. Total realized USD PnL remains N/A.</div>{analysis.wallets.map(w=><section className="panel" key={w.wallet}><div className="panel-heading"><div><h2 className="mono">{shortAddress(w.wallet)}</h2><p>{w.wallet}</p></div><span className={`tag ${w.evidence_status==="Insufficient historical data"?"":"mint"}`}>{w.evidence_status}</span></div>{w.evidence_status==="Insufficient historical data"&&<Notice>{w.closed_sales} fully matched sales; at least {w.minimum_sample} and complete pagination are required for the evidence threshold. This wallet is not labeled profitable.</Notice>}<div className="stat-grid"><div className="stat"><span>Observed trades</span><strong>{w.observed_trades}</strong><small>{w.buys} buys · {w.sells} sells</small></div><div className="stat"><span>Matched-sale win rate</span><strong>{change(w.win_rate_pct).replace(/^\+/,"")}</strong><small>{w.closed_sales} fully matched sales, gross quote units</small></div><div className="stat"><span>Average / median return</span><strong className="compact-stat">{change(w.average_return_pct)}</strong><small>Median {change(w.median_return_pct)}</small></div><div className="stat"><span>Trading frequency</span><strong>{quantity(w.trades_per_observed_day,2)}</strong><small>per requested day · {w.tokens_traded} tokens</small></div></div><div className="quality-list"><div><span>Observed matched PnL · quote units</span><b>{Object.entries(w.observed_matched_pnl_by_quote).map(([q,n])=>`${quantity(n,6)} ${q}`).join(" · ")||"N/A"}</b></div><div><span>Total realized USD PnL</span><b>N/A</b></div><div><span>Unmatched sales / partial sales</span><b>{w.unmatched_sales} / {w.partial_matched_sales}</b></div><div><span>Requested-window pagination</span><b>{w.coverage_complete?"Complete":"Incomplete · page budget reached"}</b></div></div><details><summary>Recent supported swap activity</summary><div className="table-wrap"><table><thead><tr><th>Time</th><th>Side</th><th>Token mint</th><th>Token quantity</th><th>Quote quantity / mint</th><th>Network fee (SOL)</th></tr></thead><tbody>{w.recent_activity.map(e=><tr key={e.id}><td>{utc(e.ts)}</td><td>{e.side}</td><td><Link className="text-link" href={`/markets/?mint=${e.token}`}>{shortAddress(e.token)}</Link></td><td>{quantity(e.quantity,6)}</td><td title={e.quote_mint}>{quantity(e.quote_quantity,6)} / {shortAddress(e.quote_mint)}</td><td>{quantity(e.network_fee_lamports==null?null:e.network_fee_lamports/1e9,9)}</td></tr>)}</tbody></table></div></details></section>)}
    <section className="panel"><div className="panel-heading"><h2>Create REAL research dataset</h2><Database size={20}/></div><label className="check-label"><input type="checkbox" checked={includeMarkets} onChange={e=>setIncludeMarkets(e.target.checked)} disabled={busy}/>Include historical USD prices and exit liquidity (Birdeye access required)</label><p className="body-small">Research needs complete five-minute price and liquidity observations, plus complete transaction pagination. Current market values are not inserted into past timestamps.</p><button className="button primary" disabled={busy||!histories.length} onClick={()=>void save()}><Database size={16}/>Create REAL dataset</button>{saved&&<div className="notice neutral"><div>{saved.quality.performance_ready?"Ready for evaluation.":"Incomplete dataset: performance is blocked."}<Link className="text-link" href="/datasets/">Inspect coverage</Link>{saved.quality.performance_ready&&<Link className="text-link" href="/audit/">Audit this hypothesis</Link>}</div></div>}</section>
    <section className="panel"><h2>Evidence limits</h2><ul>{analysis.limitations.map(x=><li key={x}>{x}</li>)}</ul><details><summary>Parser exclusions and provenance</summary><pre>{JSON.stringify(analysis.provenance,null,2)}</pre></details></section></>}
  </>;
}
